### PR TITLE
Update PPO2.py 

### PR DESCRIPTION
**Pull request by haloted**
This update adds saving model parameter using keyboard interrupt (Ctrl+C) during the training process. 
It is able to save the .pkl during any stages of training rather than waiting until the training update is finished.

### CODE REVIEW

**Comment by jhwangbo** [comment]
Hi Ted, thank you for contributing. I think this is a nice feature for some people but I prefer saving parameters after every N number of iterations. For publication, you want to produce a clip like this one: https://youtu.be/aTDkYFZFWug?t=90  Now, you have to kill the training in order to save the parameters. Is there any reason that you prefer this type of saving process?

**Comment by haloted** [comment]
There is actually no specific reason other than just wanting to find a quick way to save model parameters say after running the simulation for a whole night. 
I'm putting this idea out here to get some feedback and to check how to output. I will adopt your idea and try to make changes. Cheers.

**Comment by haloted** [comment]
I have updated my code as per your Youtube example. Let me know if it's okay. 

Cheers,

**Comment by jhwangbo** [comment]
Hi Ted, I just pulled your repo and tried it out. it looks great. A few minor comments
1. now ```_evaliter``` is hardcoded. Can we use ```eval_every_n``` instead? so every time we display the video, we save the parameters.
2. the keyboard interrupt doesn't save the iteration number. Can we add it as well?
3. no bracket in the ```if``` statement. Just for a consistent coding style

thx
Jemin

**Pull request closed without merging**
