### PR TITLE
PPO2.py Update on using eval_n_iter instead of hardcoding

### PR DESCRIPTION
**Pull request by haloted**
Updated PPO2.py as according to the three pointers.

### CODE REVIEW

**Comment by haloted** [comment]
Apologies for closing the other pull request, was experimenting with changing different default branches so accidentally deleted the other branches.

**Comment by haloted** [comment]
This latest commit can now adapt to different eval_n_iter, tested with 80 and 50 and produce recorded videos with saved weights in sync.

**Comment by jhwangbo** [comment]
looks great. I tested your branch and works fine on my laptop. Thx for your contribution

**Comment by haloted** [comment]
Hi Jwangbo, thanks for the merge, just to avoid confusion of future users, please remove the import math package line at the top, it's no longer needed. And the line comment on line 379  of PPO2.py, change evaliter=200 to eval_n_iter instead in the comments. Cheers,ted

**Comment by jhwangbo** [comment]
Done. I also made a few changes. Previously the parameter was saved after an update. Then it no longer corresponds to the video. And the code is shorter now after the change

**Pull request merged**
